/* SQL SERVER - API REST NODEJS */

CREATE DATABASE DB_API_REST;

USE DB_API_REST;

SELECT * FROM TM_CATEGORIA;

/* Listar Categorías */
CREATE PROCEDURE SP_LIST_CATEGORIAS
AS
BEGIN
	SELECT * FROM TM_CATEGORIA
END


/* Agregar Una Categoría */
CREATE PROCEDURE SP_INSERT_CATEGORIA
@CAT_ID INT,
@CAT_NOM VARCHAR(150),
@CAT_OBS VARCHAR(150)
AS
BEGIN
	INSERT INTO TM_CATEGORIA
		(CAT_NOM, CAT_OBS)
		VALUES
		(@CAT_NOM, @CAT_OBS)

	SELECT * FROM TM_CATEGORIA
END


/* Actualizar Una Categoría */
CREATE PROCEDURE SP_UPDATE_CATEGORIA
@CAT_ID INT,
@CAT_NOM VARCHAR(150),
@CAT_OBS VARCHAR(150)
AS
BEGIN
	UPDATE TM_CATEGORIA
	SET
		CAT_NOM = @CAT_NOM,
		CAT_OBS = @CAT_OBS
	WHERE
		CAT_ID = @CAT_ID

	SELECT * FROM TM_CATEGORIA
END